WITH
USER_COUNT AS (
    SELECT DISTINCT
        REGION
        , PLATFORM
        , EXPERIENCE
        , COUNT(DISTINCT USER_ID) AS USER_COUNT
    FROM TRANSACTIONS -- noqa: RF04
    GROUP BY
        REGION
        , PLATFORM
        , EXPERIENCE
)

SELECT *
FROM USER_COUNT;