SELECT
    EVENT_NAME
    , EVENT_DATE
    , REGION
    , EXPERIENCE
    , COUNT(*) AS COUNT
FROM TRANSACTIONS
GROUP BY
    EVENT_NAME
    , EVENT_DATE
    , REGION
    , EXPERIENCE
ORDER BY
    EVENT_NAME
    , EVENT_DATE;
